1. Import numpy as np and see the version

In [97]:
import numpy as np
import sys
np.version.version

'1.24.0'

2. How to create a 1D array?

In [8]:
# Q. Create a 1D array of numbers from 0 to 9
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. How to create a boolean array?

In [9]:
# Q. Create a 3×3 numpy array of all True’s
B = np.ones([3, 3], dtype=bool)
B

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. How to extract items that satisfy a given condition from 1D array?

In [11]:
# Q. Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1]  

array([1, 3, 5, 7, 9])

5. How to replace items that satisfy a condition with another value in numpy array?

In [13]:
# Q. Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6. How to replace items that satisfy a condition without affecting the original array?

In [17]:
# Q. Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr % 2 == 1, -1, arr)
print(out)
arr

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

7. How to reshape an array?

In [29]:
# Q. Convert a 1D array to a 2D array with 2 rows
arr = np.arange(10)
arr.reshape(2, -1) # -1 automates the number of columns

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. How to stack two arrays vertically?

In [31]:
# Q. Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. How to stack two arrays horizontally?

In [33]:
# Q. Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. How to generate custom sequences in numpy without hardcoding?

In [35]:
a = np.array([1,2,3])
a = np.r_[np.repeat(a, 3), np.tile(a, 3)]
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

11. How to get the common items between two python numpy arrays?

In [37]:
# Q. Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

12. How to remove from one array those items that exist in another?

In [39]:
# Q. From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

13. How to get the positions where elements of two arrays match?

In [41]:
# Q. Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
arr = np.where(a==b)
arr

(array([1, 3, 5, 7]),)

14. How to extract all numbers between a given range from a numpy array?

In [44]:
# Q. Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

15. How to make a python function that handles scalars to work on numpy arrays?

In [47]:
# Q. Convert the function maxx that works on two scalars, to work on two arrays.
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

16. How to swap two columns in a 2d numpy array?

In [49]:
# Q. Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
arr[:, [1, 0]] = arr[:, [0, 1]]
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

17. How to swap two rows in a 2d numpy array?

In [51]:
# Q. Swap rows 1 and 2 in the array arr:
arr = np.arange(9).reshape(3,3)
arr[[1, 0],:] = arr[[0, 1],:]
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

18. How to reverse the rows of a 2D array?

In [62]:
# Q. Reverse the rows of a 2D array arr.
arr = np.arange(9).reshape(3,3)
# or  arr[::-1]
np.flip(arr, axis=0)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

19. How to reverse the columns of a 2D array?

In [63]:
# Q. Reverse the columns of a 2D array arr.
arr = np.arange(9).reshape(3,3)
np.flip(arr, axis=1)
# or   arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

20. How to create a 2D array containing random floats between 5 and 10?

In [70]:
# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
arr = np.random.uniform(5,11, size=(5,3))
arr

array([[ 5.78437813,  7.59600176,  7.53419343],
       [ 8.79587494, 10.07767143,  9.57496146],
       [ 6.70493654,  5.8654127 ,  5.8330768 ],
       [ 7.11953946,  5.61972672,  5.19471403],
       [ 8.82166954, 10.28957365,  9.95464673]])

21. How to print only 3 decimal places in python numpy array?

In [71]:
# Q. Print or show only 3 decimal places of the numpy array rand_arr.
rand_arr = np.random.random((5,3))
np.round(rand_arr, decimals=3)

array([[0.801, 0.507, 0.245],
       [0.693, 0.744, 0.402],
       [0.949, 0.968, 0.545],
       [0.208, 0.914, 0.51 ],
       [0.858, 0.739, 0.992]])

22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [83]:
# Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

23. How to limit the number of items printed in output of numpy array?

In [89]:
# Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

24. How to print the full numpy array without truncating

In [98]:
# Q. Print the full numpy array a without truncating.
# Input
np.set_printoptions(threshold=6)
a = np.arange(15)

# Solution
np.set_printoptions(threshold=sys.maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [102]:
#Q. Import the iris dataset keeping the text intact.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

26. How to extract a particular column from 1D array of tuples?

In [105]:
# Q. Extract the text column species from the 1D iris imported in previous question.
iris[:5]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)

27. How to convert a 1d array of tuples to a 2d numpy array?

In [ ]:
https://www.machinelearningplus.com/python/101-numpy-exercises-python/